### ISSUE TITLE
Wrong icon appears in certain situations

### ISSUE THREAD

**Issue by Aktimoose** [Alphatism/ExtraIcons#1]
If I have any cube selected with an id of 142 or greater, and then exit out of the garage and enter back in, it will show whatever the last icon available in my texture pack is. (this includes the 142nd cube that's available in vanilla)

![image](https://github.com/Alphatism/ExtraIcons/assets/44620677/dd3cae2c-192f-47a8-8553-4385639ba480)

The same issue happens in-game when the 2nd player in a dual has its disappearing animation
![image](https://github.com/Alphatism/ExtraIcons/assets/44620677/733d7aae-f994-4d9a-a364-efde03f58ff0)

**Comment by Alphalaneous** [comment]
Fixed in https://github.com/Alphatism/ExtraIcons/commit/46018d430f3501c5391a62a5792da51f913d671a
