### ISSUE TITLE
idk how to use those pilst value things or whatever

### ISSUE THREAD

**Issue by dodaflopyocat** [Alphatism/ExtraIcons#2]
i dont know
https://drive.google.com/file/d/1maTaAaSGB0i03YcYGXQ8m0qxIM1UBc06/view?usp=sharing

**Comment by Alphalaneous** [comment]
This is not an issue with the mod. When you add a resource pack, you have to paste both the pngs and the plist files. If they already exist for you, just replace them both. Unless you are making your own texture pack, you do not need to be manually editing plists. Even then, there are tools to pack the textures automatically anyways.

**Comment by dodaflopyocat** [comment]
im making one of my own and dont know how to use plist
help

**Comment by Alphalaneous** [comment]
I do not make texture packs, i simply make a mod that allows the icon count to be larger. If you want help, ask a texture pack maker. This is not the place, this is for issues with the mod.

**Comment by dodaflopyocat** [comment]
ok thanks
